stages:
  - utest

before_script:
  - set

variables:
  ENV_DIR: env
  
.setup_env:
  stage: utest
  tags:
    - CYPTEST-W1064-V1
  script:
    - echo [INFO] Setup python environment
    - virtualenv ${ENV_DIR}

unit_test:
  extends: .setup_env
  tags:
    - CYPTEST-W1064-V1
  script:
    - cd
    - ${ENV_DIR}\Scripts\activate
    - pip install setuptools_scm
    - pip install setuptools_scm_git_archive
    - pip install -r dev-requirements.txt
    - pytest
    
