stages:
  - analysis
  - utest
  - btest
  - ftest

variables:
# ENV_DIR: env
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

#before_script:
#  - set
#  - python -V               # Print out python version for debugging
#  - virtualenv venv  
#  - call .\venv\Scripts\activate.bat
#  - echo [INFO] Installing python modules
#  - pip install setuptools_scm
#  - pip install setuptools_scm_git_archive
#  - pip install -r dev-requirements.txt

cache:
  paths:
    - .cache/pip
    - venv/
  
code_analysis:
  stage: analysis
  tags:
  - PYOCD-TEST-UB1804-1
  script:
    - set
    - python -V               # Print out python version for debugging
    - virtualenv venv
    - source venv/bin/activate
    - echo [INFO] Installing python modules
    - pip install setuptools_scm
    - pip install setuptools_scm_git_archive
    - pip install -r dev-requirements.txt
    - echo [INFO] Running analysys
    - python test/pylint_test.py

unit_test:
  stage: utest
  tags:
  - PYOCD-TEST-WIN1064
  script:
    - set
    - python -V               # Print out python version for debugging
    - virtualenv venv
    - call .\venv\Scripts\activate.bat
    - echo [INFO] Installing python modules
    - pip install setuptools_scm
    - pip install setuptools_scm_git_archive
    - pip install -r dev-requirements.txt
    - echo [INFO] Running unit tests
    - pytest

win_py_3.7_basic_test:
  stage: btest
  tags:
  - PYOCD-TEST-WIN1064
  dependencies:
    - unit_test
  script:
    - python -V               # Print out python version for debugging
    - virtualenv venv
    - call .\venv\Scripts\activate.bat
    - echo [INFO] Installing python modules
    - pip install setuptools_scm
    - pip install setuptools_scm_git_archive
    - pip install -r dev-requirements.txt
    - pushd test
    - echo [INFO] Running basic tests
    - python cy_basic_test.py
    
ub_py_2.7_basic_test:
  stage: btest
  tags:
  - PYOCD-TEST-UB1804-1
  dependencies:
    - unit_test
  script:
    - python -V               # Print out python version for debugging
    - virtualenv venv
    - source venv/bin/activate
    - echo [INFO] Installing python modules
    - pip install setuptools_scm
    - pip install setuptools_scm_git_archive
    - pip install -r dev-requirements.txt
    - pushd test
    - echo [INFO] Running basic tests
    - python cy_basic_test.py
    
win10_py_3.7_functional_test:
  stage: ftest
  tags:
  - PYOCD-TEST-WIN1064
  dependencies:
    - win_py_3.7_basic_test
  script:
    - python -V               # Print out python version for debugging
    - virtualenv venv
    - call .\venv\Scripts\activate.bat
    - echo [INFO] Installing python modules
    - pip install setuptools_scm
    - pip install setuptools_scm_git_archive
    - pip install -r dev-requirements.txt
    - pushd test
    - echo [INFO] Running functional tests
    - python automated_test.py
  when: manual

win7_py_2.7_functional_test:
  stage: ftest
  tags:
  - PYOCD-TEST-WIN732
  dependencies:
    - win_py_3.7_basic_test
  script:
    - python -V               # Print out python version for debugging
    - virtualenv venv
    - call .\venv\Scripts\activate.bat
    - echo [INFO] Installing python modules
    - pip install setuptools_scm
    - pip install setuptools_scm_git_archive
    - pip install -r dev-requirements.txt
    - pushd test
    - echo [INFO] Running functional tests
    - python automated_test.py
  when: manual

ub_py_2.7_functional_test:
  stage: ftest
  tags:
  - PYOCD-TEST-UB1804-1
  dependencies:
    - ub_py_2.7_basic_test
  script:
    - python -V               # Print out python version for debugging
    - virtualenv venv
    - source venv/bin/activate
    - echo [INFO] Installing python modules
    - pip install setuptools_scm
    - pip install setuptools_scm_git_archive
    - pip install -r dev-requirements.txt
    - pushd test
    - echo [INFO] Running functional tests
    - python automated_test.py
  when: manual
  
ub_py_3.7_functional_test:
  stage: ftest
  tags:
  - PYOCD-TEST-UB1804
  dependencies:
    - ub_py_2.7_basic_test
  script:
    - python3 -V               # Print out python version for debugging
    - virtualenv venv
    - source venv/bin/activate
    - echo [INFO] Installing python modules
    - pip3 install setuptools_scm
    - pip3 install setuptools_scm_git_archive
    - pip3 install -r dev-requirements.txt
    - pushd test
    - echo [INFO] Running functional tests
    - python3 automated_test.py
  when: manual
  
mac1013_py_2.7_functional_test:
  stage: ftest
  tags:
  - PYOCD-TEST-MAC1013
  script:
    - python -V               # Print out python version for debugging
    - virtualenv venv
    - source venv/bin/activate
    - echo [INFO] Installing python modules
    - pip install setuptools_scm
    - pip install setuptools_scm_git_archive
    - pip install -r dev-requirements.txt
    - pushd test
    - echo [INFO] Running functional tests
    - python automated_test.py
  when: manual
  
mac1014_py_3.7_functional_test:
  stage: ftest
  tags:
  - PYOCD-TEST-MAC1014
  script:
    - python3 -V               # Print out python version for debugging
    - virtualenv venv
    - source venv/bin/activate
    - echo [INFO] Installing python modules
    - pip install setuptools_scm
    - pip install setuptools_scm_git_archive
    - pip install -r dev-requirements.txt
    - pushd test
    - echo [INFO] Running functional tests
    - python3 automated_test.py
  when: manual