stages:
  - utest

before_script:
  - set
  - uname -s

#variables:
#  ENV_DIR: env
  
unit_test:
  stage: utest
  tags:
    - CYPTEST-W1064-V1
  script:
    - cd
    - echo [INFO] Setup python environment
    - virtualenv env
    - ./env/Scripts/activate
    - pip install setuptools_scm
    - pip install setuptools_scm_git_archive
    - pip install -r dev-requirements.txt
    - echo [INFO] Running unit tests
    - pytest
    
