stages:
  - analysis
  - utest
  - ftest

variables:
# ENV_DIR: env
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

before_script:
  - set
  - python -V               # Print out python version for debugging
  - virtualenv venv  
  - call .\venv\Scripts\activate.bat
  - echo [INFO] Installing python modules
  - pip install setuptools_scm
  - pip install setuptools_scm_git_archive
  - pip install -r dev-requirements.txt

cache:
  paths:
    - .cache/pip
    - venv/
  
code_analysis:
  stage: analysis
  tags:
  - CYPTEST-W1064-V1
  script:
    - python test/pylint_test.py

unit_test:
  stage: utest
  tags:
  - CYPTEST-W1064-V1
  script:
    - cd
    - echo [INFO] Running unit tests
    - pytest

functional_test:
  stage: ftest
  tags:
  - CYPTEST-W1064-V1
  dependencies:
    - unit_test
  script:
    - pushd test
    - echo [INFO] Running functional tests
    # - python automated_test.py -b 190100008b131509028b131500000000000000002e127069
    - python automated_test.py -b 190100008b13151c028b131500000000000000002e127069
