stages:
  - analysis
  - utest
  - btest

variables:
# ENV_DIR: env
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

#before_script:
#  - set
#  - python -V               # Print out python version for debugging
#  - virtualenv venv  
#  - call .\venv\Scripts\activate.bat
#  - echo [INFO] Installing python modules
#  - pip install setuptools_scm
#  - pip install setuptools_scm_git_archive
#  - pip install -r dev-requirements.txt

cache:
  paths:
    - .cache/pip
    - venv/
  
code_analysis:
  stage: analysis
  tags:
  - PYOCD-TEST-UB1804-1
  script:
    - set
    - python -V               # Print out python version for debugging
    - virtualenv venv
    - source venv/bin/activate
    - echo [INFO] Installing python modules
    - pip install setuptools_scm
    - pip install setuptools_scm_git_archive
    - pip install -r dev-requirements.txt
    - echo [INFO] Running analysys
    - python test/pylint_test.py

unit_test:
  stage: utest
  tags:
  - PYOCD-TEST-WIN1064
  script:
    - set
    - python -V               # Print out python version for debugging
    - virtualenv venv
    - call .\venv\Scripts\activate.bat
    - echo [INFO] Installing python modules
    - pip install setuptools_scm
    - pip install setuptools_scm_git_archive
    - pip install -r dev-requirements.txt
    - cd
    - echo [INFO] Running unit tests
    - pytest

basic_test_win:
  stage: btest
  tags:
  - PYOCD-TEST-WIN1064
  #dependencies:
  #  - unit_test_win
  script:
    - pushd test
    - echo [INFO] Running basic tests
    - python cy_basic_test.py
    
basic_test_ub:
  stage: btest
  tags:
  - PYOCD-TEST-UB1804-1
  #dependencies:
  #  - unit_test_ub
  script:
    - pushd test
    - echo [INFO] Running basic tests
    - python cy_basic_test.py