stages:
  - utest

before_script:
  - set
  - uname -s
  - id

#variables:
#  ENV_DIR: env
  
unit_test:
  stage: utest
  tags:
    - CYPTEST-W1064-V1
  script:
    - cd
    - echo [INFO] Setup python environment
    - virtualenv env
    - call .\env\Scripts\activate.bat
    - echo [INFO] Installing python modules
    - pip install setuptools_scm
    - pip install setuptools_scm_git_archive
    - pip install -r dev-requirements.txt
    - echo [INFO] Running unit tests
    - pytest
    
